### ISSUE TITLE
crypto-bigint: feature wishlist tracking ticket

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/crypto-bigint#1]
This is a ticket for tracking desired new features for `crypto-bigint` and which algorithms should be used in order to implement particular features.

Unless otherwise stated, these features are implied to be for the `UInt` type.

- [ ] signed integers
- [x] addition/subtraction
- [ ] multiplication algorithms
  - [x] "grade school"
  - [ ] Karatsuba
  - [ ] Montgomery/modmul
- [ ] modpow
- [ ] inversions
- [ ] sqrt
- [ ] bitwise operations (request other ops in comments)
  - [ ] shift
  - [ ] rotate
  - [ ] XOR
- [ ] fields mod n (i.e. wrapper newtypes for `UInt`)
- [ ] constant-time division
  - [ ] by 2 (useful for `elliptic-curve` crates)
  - [ ] arbitrary
- [x] `subtle` comparisons
  - [x]  `ConstantTimeEq`
  - [x] `ConstantTimeGreater`
  - [x] `ConstantTimeLess`
- [ ] CRT (algorithms listed below)
  - [ ] [Smooth RSA-CRT](https://eprint.iacr.org/2007/039)
  - ~~https://eprint.iacr.org/2020/1507~~ (note: [appears to be covered by patents](https://github.com/RustCrypto/RSA/issues/93))
- [ ] LCM
- [ ] GCD (algorithms listed below)
  - [safegcd](https://gcd.cr.yp.to/safegcd-20190413.pdf)
  - [safegcd-bounds](https://github.com/sipa/safegcd-bounds)
- [ ] RNG
  - [x] ~~random < n~~ RustCrypto/utils#508
  - [ ] [better random < n](https://github.com/apple/swift/pull/39143)
  - [ ] random prime
- [ ] SIMD backends
  - [ ] AVX2
  - [ ] NEON

**Comment by mikelodder7** [comment]
Need to update this list with completed features @tarcieri

**Comment by tarcieri** [comment]
@mikelodder7 should be updated now

**Comment by newpavlov** [comment]
Modular exponentiation?

**Comment by Sc00bz** [comment]
It's under "modular arithmetic" as "pow". Hmm "sqrt" and "inversions" should be under the "modular arithmetic" section.

**Comment by tarcieri** [comment]
Sorry, I reorganized the modular arithmetic section, and missed a few things along the way.

Note there is `sqrt` under modular arithmetic. However, I'll move inversions there.

**Comment by Sc00bz** [comment]
Oh I missed that. Is the other "sqrt" for `floor(sqrt(n))`?

P.S. I just re-found the edit history button and "pow" was added after @newpavlov's question. I thought there was edit history but it wasn't in the "…" menu.

**Comment by mikelodder7** [comment]
Both are important. Integer sqrt is used in the Lucas test for prime numbers for example.

**Comment by dignifiedquire** [comment]
I would suggest having the different algorithms behind specific methods, such that downstream implementors can choose the algorithm, eg `fn sqrt_tonelli_shank()`.

**Comment by fjarri** [comment]
Seems like it can be updated, all the modular arithmetic is done, and random primes are implemented by `crypto-primes`.

**Comment by pinkforest** [comment]
Should there be a straightforward `pow` for `Uint` and `BoxedUint` types - like
- https://docs.rs/num-bigint-dig/latest/src/num_bigint_dig/biguint.rs.html#501

**Comment by tarcieri** [comment]
@pinkforest all of the functionality in this crate is directly motivated by a specific cryptographic algorithm the functionality is intended to implement. What would be the purpose? Modular exponentiation is useful for DSA and RSA, but to my knowledge we have no use case for a non-modular `pow`.

We also implement fixed, not arbitrary, precision, and a non-modular `pow` can quickly overflow fixed-precision integers.

**Comment by pinkforest** [comment]
Thanks - Yeah my naive use-case was 1:1 porting 1:1 from existing vartime bigint and I think that was naive of me to do agreed - 

Specifically deterministic RSA prime factor recovery as described by [NIST.SP.800-56Br2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf) Appendix C.2.

I should have re-evaluated it given the type for `e` has maximum size already and I can just simply do X::from(65536) to check minimum instead of ad-hoc two.pow(16) as you noted correctly - thanks!

**Comment by erik-3milabs** [comment]
Note: #624 was superseeded by #700.

**Comment by Fethbita** [comment]
I am currently using an LCM implementation like so:

```rust
use crypto_bigint::{ConcatMixed, NonZero, Uint};

pub fn lcm<const LIMBS: usize, const LIMBS_TIMES_TWO: usize>(
    a: &NonZero<Uint<LIMBS>>,
    b: &NonZero<Uint<LIMBS>>,
) -> NonZero<Uint<LIMBS_TIMES_TWO>>
where
    Uint<LIMBS>: ConcatMixed<Uint<LIMBS>, MixedOutput = Uint<LIMBS_TIMES_TWO>>,
{
    let gcd = NonZero::new(*a.gcd_uint(b)).expect("gcd is non zero");
    let lcm: NonZero<Uint<LIMBS_TIMES_TWO>> = a
        .wrapping_div(&gcd)
        .concatenating_mul(b)
        .to_nz()
        .expect("This result can't be zero");
    lcm
}

#[cfg(test)]
mod tests {
    use super::*;
    use crypto_bigint::{U4096, U8192};

    #[test]
    fn test_lcm_common_values() {
        // Test: lcm(6, 9) = 18
        let a = NonZero::new(U4096::from_u8(6)).expect("Non-zero input");
        let b = NonZero::new(U4096::from_u8(9)).expect("Non-zero input");
        let result = lcm::<_, _>(&a, &b);
        assert_eq!(
            result,
            NonZero::new(U8192::from_u8(18)).expect("Non-zero input")
        );

        // Test: lcm(12, 18) = 36
        let a = NonZero::new(U4096::from_u8(12)).expect("Non-zero input");
        let b = NonZero::new(U4096::from_u8(18)).expect("Non-zero input");
        let result = lcm::<_, _>(&a, &b);
        assert_eq!(
            result,
            NonZero::new(U8192::from_u8(36)).expect("Non-zero input")
        );
    }
}
```

I wonder if it would be possible to have LCM in this new release since it only depends on `gcd` `mul` and `div` operations which are all supported.

**Comment by tarcieri** [comment]
@Fethbita you can open a PR and we can discuss

**Comment by Fethbita** [comment]
Created #1028 for it.

**Comment by kayabaNerve** [comment]
Not sure if this the absolute best issue for me to post this, but it seems as good as any.

I'm in _love_ with the new `UintRef` type and it's almost exactly what I've wanted for ~a year and a half now. In some of my own code, I defined a `trait Limbs` for `AsRef<[Limb]>` (and other similar methods), so when I perform a certain reduction algorithm, I can dynamically decrease the size of the integers as the reduction occurs. `UintRef` is the first-party version with an incredible amount of functionality.

I think there's some internal functions for multiplication/division that I've wanted exposed over the years, but I can't immediately remember which they were. The reason was presumably for mixed-length multiplications, as I believe there's an internal function which takes two slices and a scratchpad, but all public methods are fixed. To that end, most of my feature wishlist is simply the expansion of `UintRef` and similar (including methods which require scratch space). I think I also have a few cases where I know a division is perfect (sans remainder), and I am curious if that enables a non-trivially faster algorithm.

After that, as I'm sure has been stated infinitely, my 'wishlist' is really just for `crypto-bigint` to be faster, but it's been incredibly remarkable to watch these past few years to the point I don't even have too many explicit goals. I'd like to especially note not only all of the work done on Montgomery forms, but also the work on the optimized binary XGCD. I almost feel like the remaining optimizations will be:

1) Callers writing their code better, which is what I love `UintRef` for
2) SIMD

This message is really just to show my appreciation for the years of work, and also happiness with the direction, rather to comment anything too explicitly. Thank you again!
