### ISSUE TITLE
Tracking issue for `BoxedUint`/`BoxedResidue` missing features

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/crypto-bigint#348]
I recently spiked out both of these types, but there are likely to be plenty of small gaps feature-wise.

This is a tracking issue for those gaps:

- [x] [Impl `RandomMod` for `BoxedUint`](https://github.com/RustCrypto/crypto-bigint/pull/349)
- [ ] Trait for abstracting over `*Residue` types

cc @dignifiedquire @fjarri

**Comment by dignifiedquire** [comment]
- Comparisons between `NonZero<BoxedUint>` and `BoxedUint`
- `impl Hash for BoxedUint`

**Comment by dignifiedquire** [comment]
- [ ] Impl Hash for `NonZero<BoxedUint>`

**Comment by tarcieri** [comment]
Aside from the `*Residue`-like trait, which we can discuss in #431/#448, the `Boxed*` types are pretty feature-complete at this point. Closing.
