### ISSUE TITLE
Bernstein-Yang: constant-time issues

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/crypto-bigint#627]
This is a tracking issue for various problems with our Bernstein-Yang implementation where it operates in a non-constant-time manner:

- [x] `Int62L::eq` returns `bool` that's branched on in various places ([#630](https://github.com/RustCrypto/crypto-bigint/pull/630), [#631](https://github.com/RustCrypto/crypto-bigint/pull/631))
- [x] `Int62L::is_negative` returns `bool` that's branched on in various places ([#628](https://github.com/RustCrypto/crypto-bigint/pull/628), [#629](https://github.com/RustCrypto/crypto-bigint/pull/628))
- [x] `gcd` uses a data-dependent loop ([#632](https://github.com/RustCrypto/crypto-bigint/pull/632), [#635](https://github.com/RustCrypto/crypto-bigint/pull/635))

Note: as the implementation has never received a stable release, we don't consider this issue security critical.

**Comment by tarcieri** [comment]
All of the timing variability I'm aware of has been removed. Closing this.
