### ISSUE TITLE
`Int` feature tracking ticket

### ISSUE THREAD

**Issue by erik-3milabs** [RustCrypto/crypto-bigint#700]
### Related
  - #1 (feature request), and 
  - #624 (initial discussion).
  - #694 (abandoned attempt involving sign-magnitude representation),

### Features
- [x] `add`, `sub`, `mul`, `div` #695
- [x] `and`, `or`, `xor`, `not`, `shl`, `shr` #697
- [x] `Int::square` operations #734 
- [x] `vartime` division #735
- [x] `mul_uint`, `div_uint` #736 
- [ ] Encoding support (`from_be_slice`, `from_le_slice`)
- [x] `inv_mod` #737 
- [x] `gcd` #698   
- [ ] `xgcd`
- [ ] prop-tests (see also https://github.com/RustCrypto/crypto-bigint/pull/695#issuecomment-2438256609)

**Comment by ycscaly** [comment]
@tarcieri with #695 merged to signed-int, whats the plan for this feature? Specifically, will it be included in the next release? Could be helpful esp. because of  comparability other crates like elliptic-curves depending on crypto-bigint

**Comment by tarcieri** [comment]
@ycscaly yeah, we should be able to get at least a preliminary implementation into the release and then we can additively improve it.

I went ahead and added it to the list in #681

**Comment by tarcieri** [comment]
I'm planning on trying to wrap up `crypto-bigint` v0.6.0 stable, and I'd like to save this for `crypto-bigint` v0.7, FYI.

Fortunately, all work is happening on the [`signed-int`](https://github.com/RustCrypto/crypto-bigint/tree/signed-int) branch.

**Comment by ycscaly** [comment]
> I'm planning on trying to wrap up `crypto-bigint` v0.6.0 stable, and I'd like to save this for `crypto-bigint` v0.7, FYI.
> 
> Fortunately, all work is happening on the [`signed-int`](https://github.com/RustCrypto/crypto-bigint/tree/signed-int) branch.

Why can't we have the signed integers on 0.6? There's quite a bit already implemented here, and we are actively using it.
We are planning to lunch our product very soon, and would be better to have this as part of a release if possible.

Thanks!

**Comment by tarcieri** [comment]
Aah, well then. We can potentially merge the `signed-int` branch, although there are still a few outstanding PRs and work seems to have stalled.

If it doesn't make it in, we'll be able to merge it in a v0.7 release, which I would expect some time in Q2 2025.

**Comment by fjarri** [comment]
What breaking changes do signed integers introduce?

**Comment by tarcieri** [comment]
As far as I'm aware, they're completely additive

**Comment by fjarri** [comment]
So they can probably be added in 0.6.1 which would be much easier to handle in the dependencies?

**Comment by tarcieri** [comment]
Sure, no need to block a v0.6 release. It would probably be good to get a PR to merge the branch open first so we can confirm there aren't any breaking changes, though.

**Comment by ycscaly** [comment]
> Sure, no need to block a v0.6 release. It would probably be good to get a PR to merge the branch open first so we can confirm there aren't any breaking changes, though.

Sounds like a good in-between solution.

@erik-3milabs can you open this PR?

**Comment by tarcieri** [comment]
I'm going to go ahead and close this as complete since the bulk of signed integer support has been merged.

If there is additional functionality you'd still like added, please open new issues.
